export { default as Header } from './header/Header';
export { default as Footer } from './footer/Footer';
export { default as HomePage } from './home-page/HomePage';
export { default as CarsSearchView } from './cars-search-view/CarsSearchView';
export { default as CarsListView } from './cars-list-view/CarsListView';
export { default as CarsFilter } from './cars-filter/CarsFilter';
export { default as CarDetails } from './car-details/CarDetails';
export { default as PageNotFound } from './page-not-found/PageNotFound';
export { default as Loader } from './loader/Loader';
